### ISSUE TITLE
Missing weather Icon for current day

### ISSUE THREAD

**Issue by kersten-lohmeyer** [FL550/dwd_weather#138]
See here:
<img width="408" alt="image" src="https://github.com/user-attachments/assets/36ec2c4d-6642-426e-8943-0da0d3d3e2fc">

Most recent integration and Home Assistant version.

**Comment by sejoki** [comment]
Noticed it too this morning, the daily forecast doesn't provide the correct data. Instead of 'sunny', it shows up as 'clear-night'. Probably because it applies the condition at the time of the daily forecast, which is always midnight. 
The missing icon is just a symptom of that, notice how for Wednesday, the daily forecast has a moon instead of a sun.

`    - datetime: "2024-08-26T00:00:00Z"`
`      condition: clear-night`

vs the met.no integration:
`    - condition: sunny`
`      datetime: "2024-08-26T10:00:00+00:00"`

**Comment by FL550** [comment]
Thank you both for reporting.

I know where this is coming from. I'll fix this as soon as possible. In the meantime I marked the latest version as beta. 

Best regards

**Comment by nicknol** [comment]
Hi, 
I noticed that the `condition` for the current day is empty in the `forecast`, but it's set properly for the next days. Is this issue related?

```
            "forecast": [
              {
                "datetime": "2024-08-27T00:00:00Z",
                "condition": null,
                "wind_bearing": 114.86,
                "wind_gust_speed": 24.1,
                "uv_index": 5,
                "precipitation_probability": null,
                "temperature": 26,
                "templow": 14,
                "wind_speed": 11.1,
                "precipitation": 0
              },
```

**Comment by FL550** [comment]
@kersten-lohmeyer @sejoki @nicknol 
I just released a new version, which addresses this issue. Should now be resolved.

**Comment by kersten-lohmeyer** [comment]
Looks good now. Thank you very much!
