### ISSUE TITLE
Merge integration into HA

### ISSUE THREAD

**Issue by tpulatha** [FL550/dwd_weather#37]
I saw a closed issue about adding this integration into Home Assistant. Is there any reason why this was not followed up on? Happy to help, if any help is needed. I really would like to have it as part of "standard" HA, as in my opinion it's the best weather integration for Germany.

**Comment by FL550** [comment]
Hey, thanks for the feedback. The issue was closed because it includes some work which nobody was willing to do 😃 The other reason was, that I am then limited in providing updates by the release cycles of HA. Right now, I can provide updates within minutes if something goes wrong or needs refinement. 

What would be the benefit for you, if it's included in HA?

**Comment by tpulatha** [comment]
I run multiple home assistant instances and therefore am reluctant to install non standard integrations due to maintainability. It’s just much easier to receive the updates with ha core. Also, there is no proper DWD integration in HA, which is a shame. 

Happy to help, if there is anything I can do
