### ISSUE TITLE
How often should entities be updated?

### ISSUE THREAD

**Issue by nicolazilio** [FL550/dwd_weather#64]
## Version of home_assistant
 2023.3.6

## Version of the custom_component
1.2.25

## Describe the bug

I would expect the integration to update its data every minute (?,  see [here](https://github.com/FL550/dwd_weather/blob/f3eb86f2ac850c9fe3b59dd2bf30494758c50100/custom_components/dwd_weather/const.py#L13)), yet in my case it updates exactly at the start of every hour (I haven't set any parameters other than the station ID). Is this the expected behaviour or not?

BTW, thanks a lot for developing this integration, it's great!

**Comment by FL550** [comment]
Hi, this is intended behavior, as the data is only provided on an hourly basis. 

The checking interval of 1 minutes is there, to make sure using the most current data applicable. 

One thing to mention as well is, that the displayed data is only a forecast for the specific hour, which is calculated by DWD every 6 hours. Actual measurements are not possible, since there are only very few weather stations available and these also with a delay of 1 hour. The forecasted values are nevertheless pretty accurate.
